#%RAML 1.0 DataType
type:
    properties:
      Gender__c: string
      Id__c: integer
      Phone_Number__c: string
      Name__c: string
      Address__c: string
      Email__c: string
      Lattitud__c: string
      Longitude__c: string